-- ============================================================
-- Gulit Market — seed data
-- Realistic but non-exhaustive Ethiopian location/category tree,
-- a handful of demo accounts, and sample listings.
-- Password for all demo accounts is: password123
-- (bcrypt hash generated by backend/src/utils/hashPassword.js)
-- ============================================================

SET NAMES utf8mb4;

-- ------------------------------------------------------------
-- roles
-- ------------------------------------------------------------
INSERT INTO roles (id, name) VALUES
  (1, 'customer'),
  (2, 'seller'),
  (3, 'admin')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- ------------------------------------------------------------
-- locations (country -> city -> district)
-- ------------------------------------------------------------
INSERT INTO locations (id, parent_id, name, name_am, level) VALUES
  (1, NULL, 'Ethiopia', 'ኢትዮጵያ', 'country');

INSERT INTO locations (id, parent_id, name, name_am, level) VALUES
  (2, 1, 'Addis Ababa', 'አዲስ አበባ', 'city'),
  (3, 1, 'Dire Dawa', 'ድሬ ዳዋ', 'city'),
  (4, 1, 'Hawassa', 'ሀዋሳ', 'city'),
  (5, 1, 'Bahir Dar', 'ባህር ዳር', 'city'),
  (6, 1, 'Gondar', 'ጎንደር', 'city'),
  (7, 1, 'Mekelle', 'መቀሌ', 'city'),
  (8, 1, 'Adama', 'አዳማ', 'city'),
  (9, 1, 'Jimma', 'ጅማ', 'city');

INSERT INTO locations (id, parent_id, name, name_am, level) VALUES
  (10, 2, 'Bole', 'ቦሌ', 'district'),
  (11, 2, 'Yeka', 'የካ', 'district'),
  (12, 2, 'Kirkos', 'ቂርቆስ', 'district'),
  (13, 2, 'Arada', 'አራዳ', 'district'),
  (14, 2, 'Gulele', 'ጉለሌ', 'district'),
  (15, 2, 'Lideta', 'ልደታ', 'district'),
  (16, 2, 'Nifas Silk-Lafto', 'ንፋስ ስልክ-ላፍቶ', 'district'),
  (17, 2, 'Kolfe Keranio', 'ኮልፌ ቀራንዮ', 'district');

-- ------------------------------------------------------------
-- categories (top-level + subcategories)
-- ------------------------------------------------------------
INSERT INTO categories (id, parent_id, name, name_am, slug, icon) VALUES
  (1, NULL, 'Electronics', 'ኤሌክትሮኒክስ', 'electronics', 'cpu'),
  (2, NULL, 'Phones & Tablets', 'ስልኮች እና ታብሌቶች', 'phones-tablets', 'smartphone'),
  (3, NULL, 'Vehicles', 'ተሽከርካሪዎች', 'vehicles', 'car'),
  (4, NULL, 'Property', 'ንብረት', 'property', 'home'),
  (5, NULL, 'Fashion', 'ፋሽን', 'fashion', 'shirt'),
  (6, NULL, 'Furniture', 'የቤት እቃዎች', 'furniture', 'armchair'),
  (7, NULL, 'Home & Garden', 'ቤት እና የአትክልት ስፍራ', 'home-garden', 'flower'),
  (8, NULL, 'Coffee & Food', 'ቡና እና ምግብ', 'coffee-food', 'coffee'),
  (9, NULL, 'Beauty', 'ውበት', 'beauty', 'sparkles'),
  (10, NULL, 'Sports', 'ስፖርት', 'sports', 'dumbbell'),
  (11, NULL, 'Kids & Baby', 'ልጆች እና ህጻናት', 'kids-baby', 'baby'),
  (12, NULL, 'Books', 'መጻሕፍት', 'books', 'book'),
  (13, NULL, 'Services', 'አገልግሎቶች', 'services', 'wrench'),
  (14, NULL, 'Jobs', 'ስራዎች', 'jobs', 'briefcase'),
  (15, NULL, 'Agriculture', 'ግብርና', 'agriculture', 'wheat'),
  (16, NULL, 'Construction', 'ግንባታ', 'construction', 'hard-hat'),
  (17, NULL, 'Other', 'ሌላ', 'other', 'grid');

INSERT INTO categories (id, parent_id, name, name_am, slug, icon) VALUES
  (20, 2, 'iPhone', NULL, 'phones-iphone', NULL),
  (21, 2, 'Samsung', NULL, 'phones-samsung', NULL),
  (22, 2, 'Tecno', NULL, 'phones-tecno', NULL),
  (23, 2, 'Infinix', NULL, 'phones-infinix', NULL),
  (24, 2, 'Accessories', NULL, 'phones-accessories', NULL),
  (30, 3, 'Cars', NULL, 'vehicles-cars', NULL),
  (31, 3, 'Motorcycles', NULL, 'vehicles-motorcycles', NULL),
  (32, 3, 'Trucks', NULL, 'vehicles-trucks', NULL),
  (33, 3, 'Parts', NULL, 'vehicles-parts', NULL),
  (40, 5, 'Habesha Kemis', 'የሐበሻ ቀሚስ', 'fashion-habesha-kemis', NULL),
  (41, 5, 'Netela', 'ነጠላ', 'fashion-netela', NULL),
  (42, 5, 'Shoes', NULL, 'fashion-shoes', NULL),
  (43, 5, 'Accessories', NULL, 'fashion-accessories', NULL);

-- ------------------------------------------------------------
-- demo users
-- password_hash below is bcrypt('password123', 10)
-- ------------------------------------------------------------
INSERT INTO users (id, role_id, full_name, email, phone, password_hash, is_active) VALUES
  (1, 1, 'Bethlehem Tadesse', 'buyer@example.com', '+251911000001',
   '$2a$10$yGA73QMI6QS.pu68pjutx.UjXGa6i31fGB5.Lv1ZFGq3GZLRcKh1W', 1),
  (2, 2, 'Shiro Meda Master Weavers Guild', 'seller@example.com', '+251911000002',
   '$2a$10$yGA73QMI6QS.pu68pjutx.UjXGa6i31fGB5.Lv1ZFGq3GZLRcKh1W', 1),
  (3, 3, 'Gulit Market Admin', 'admin@example.com', '+251911000003',
   '$2a$10$yGA73QMI6QS.pu68pjutx.UjXGa6i31fGB5.Lv1ZFGq3GZLRcKh1W', 1);

INSERT INTO seller_profiles (user_id, store_name, store_name_am, bio, location_id, is_verified, rating, review_count) VALUES
  (2, 'Shiro Meda Master Weavers Guild', 'የሽሮ ሜዳ የሸማ ማህበር',
   'Traditional Habesha Kemis, hand-woven in Addis Ababa since 1998.', 10, 1, 4.9, 92);

-- ------------------------------------------------------------
-- sample listings
-- ------------------------------------------------------------
INSERT INTO listings (id, seller_id, category_id, location_id, title, title_am, description, price_etb, condition_type, is_negotiable, status, is_featured) VALUES
  (1, 2, 40, 10,
   'Royal Gondar Velvet & Gold Tibeb Habesha Kemis',
   'የጎንደር ንግሥት ቬልቬት የሐበሻ ቀሚስ',
   'Hand-spun from pure organic Menen cotton with royal burgundy velvet paneling and 24k gold-thread embroidery. Includes matching Netela.',
   45000.00, 'new', 1, 'active', 1),
  (2, 2, 8, 9,
   'Jimma Highland Specialty Coffee Beans (Washed, Medium Roast)',
   'የጅማ ደጋማ ልዩ ቡና',
   'Single-origin washed Arabica from the birthplace of coffee. Bright citrus acidity with a jasmine finish. 250g bag.',
   850.00, 'new', 0, 'active', 1),
  (3, 2, 8, 2,
   'Authentic Berbere Spice Blend (Sun-Dried, Stone-Ground)',
   'የቤርበሬ ቅመም',
   'Traditional Ethiopian berbere blend, sun-dried chilies stone-ground with over a dozen spices. 400g pack.',
   320.00, 'new', 0, 'active', 0),
  (4, 2, 6, 2,
   'Handmade Jebena Coffee Ceremony Set',
   'የጀበና ቡና ስነ ስርዓት ስብስብ',
   'Complete clay Jebena coffee pot with matching sini cups and rekebot tray for the full ceremony.',
   2800.00, 'new', 1, 'active', 1),
  (5, 2, 30, 10,
   '2023 Toyota Corolla Cross Hybrid',
   NULL,
   'Low-mileage hybrid SUV, single owner, full service history. 12,000 km.',
   6800000.00, 'like_new', 1, 'active', 0),
  (6, 2, 4, 10,
   '2-Bedroom Apartment, Bole Atlas',
   NULL,
   'Modern 2-bedroom apartment near Bole Atlas, 24/7 security, elevator access.',
   9500000.00, 'new', 0, 'active', 0);

INSERT INTO listing_images (listing_id, url, sort_order) VALUES
  (1, '/placeholder-images/habesha_kemis_royal.jpg', 0),
  (2, '/placeholder-images/ethiopian_coffee_beans.jpg', 0),
  (3, '/placeholder-images/berbere_ethiopian_spices.jpg', 0),
  (4, '/placeholder-images/jebena_coffee_set.jpg', 0),
  (5, '/placeholder-images/toyota_corolla_cross.jpg', 0),
  (6, '/placeholder-images/bole_atlas_apartment.jpg', 0);
